version: '3.8'

services:
  # MySQL数据库
  mysql:
    image: mysql:8.0
    container_name: baby_monitor_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-password}
      MYSQL_DATABASE: ${MYSQL_DATABASE:-baby_monitor}
      MYSQL_USER: ${MYSQL_USER:-baby_monitor}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-password}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./backend/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - baby_monitor_network
    command: --default-authentication-plugin=mysql_native_password

  # Redis缓存
  redis:
    image: redis:7-alpine
    container_name: baby_monitor_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - baby_monitor_network
    command: redis-server --appendonly yes

  # FastAPI应用
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: baby_monitor_backend
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=mysql+pymysql://${MYSQL_USER:-baby_monitor}:${MYSQL_PASSWORD:-password}@mysql:3306/${MYSQL_DATABASE:-baby_monitor}
      - REDIS_URL=redis://redis:6379
      - SECRET_KEY=${SECRET_KEY:-your-secret-key-change-in-production}
      - DEBUG=${DEBUG:-False}
    volumes:
      - ./backend/uploads:/app/uploads
      - ./backend/logs:/app/logs
      - ./backend/models:/app/models
    depends_on:
      - mysql
      - redis
    networks:
      - baby_monitor_network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3

  # Nginx反向代理
  nginx:
    image: nginx:alpine
    container_name: baby_monitor_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/ssl:/etc/nginx/ssl
    depends_on:
      - backend
    networks:
      - baby_monitor_network

volumes:
  mysql_data:
  redis_data:

networks:
  baby_monitor_network:
    driver: bridge
